import { loadFont as loadAnton } from "@remotion/google-fonts/Anton";
import { loadFont as loadSpaceMono } from "@remotion/google-fonts/SpaceMono";
import { WIDTH, HEIGHT, FPS } from "../lib/safeArea";
import type { CaptionStyle } from "../lib/Captions";
import type { AudioSpec } from "../lib/AudioBed";
import type { ChartBox } from "../lib/dataviz";
import voTiming from "./vo-timing.json";
import sceneOrder from "./scenes.json";

// F-003 — The birthday paradox. The first effective_style: d3 video. Generated by
// remotion-codegen on the shared lib (lib/dataviz GrowthCurve helpers). Duration via
// calculateMetadata(vo-timing.total) — no DURATION const.

export { WIDTH, HEIGHT, FPS };
export const TOTAL: number = voTiming.total;

export const { fontFamily: ANTON } = loadAnton("normal", { weights: ["400"], subsets: ["latin"] });
export const { fontFamily: MONO } = loadSpaceMono("normal", { weights: ["400", "700"], subsets: ["latin"] });

// ---- Colors (deep-ocean depth; cyan curve; gold payoff at the 50%x23 crossing) ----
export const COLORS = {
  bgTop: "#0A1230",
  bgBottom: "#1B2C5A",
  glow: "#2A3F7A",
  nebula: "#13204A",
  text: "#F2F6FF",
  accent: "#46C6FF", // curve
  gold: "#FFC83D", // 50% gridline + x=23 marker + payoff
  rule: "#5B6BA8",
} as const;

// ---- The probability curve (SCALE-HONEST, computed from the verified formula) ----
// CURVE[n] = P(at least two of n share a birthday) * 100, for n = 0..70.
// P(n) = (1 - prod_{k=0}^{n-1} (365-k)/365) * 100. Verified: CURVE[23] = 50.73,
// CURVE[70] = 99.92 (matches 01-verified-facts.md). Dense sampling => the GrowthCurve
// x-index == group size, so the 50% gridline crosses at the true x=23.
const birthdayCurve = (): number[] => {
  const out: number[] = [];
  let q = 1;
  for (let n = 0; n <= 70; n++) {
    if (n > 0) q *= (365 - (n - 1)) / 365;
    out.push((1 - q) * 100);
  }
  return out;
};
export const CURVE: number[] = birthdayCurve();
export const N_MAX = 70; // x domain [0, 70]
export const CROSS_N = 23; // the 50% crossing (CURVE[23] = 50.7%)

// The 9 SOURCED anchor nodes (group size -> probability%), drawn as lit dots on the curve.
export const NODES: { n: number; p: number }[] = [
  { n: 10, p: 11.7 },
  { n: 20, p: 41.1 },
  { n: 23, p: 50.7 },
  { n: 30, p: 70.6 },
  { n: 40, p: 89.1 },
  { n: 50, p: 97.0 },
  { n: 60, p: 99.4 },
  { n: 70, p: 99.9 },
];

// ---- Chart geometry (the curve fills the center band; scale-honest by construction) ----
export const CHART_BOX: ChartBox = { x: 96, y: 700, w: 888, h: 520 };
// Hero number in the UPPER band (above the curve); kicker just below it; both clear of
// the chart (y≥700) and the captions (bottom). No band overlaps.
export const Y = { hero: 250, kicker: 588, fragment: 1300 } as const;

// ---- Scene ranges read STRAIGHT from scenes.json (single source; check-tiling validates). ----
type SceneName = "hook" | "beat1" | "beat2" | "beat3" | "beat4" | "beat5" | "loopBack";
const buildScenes = (): Record<SceneName, { from: number; duration: number }> => {
  const out = {} as Record<SceneName, { from: number; duration: number }>;
  for (const s of sceneOrder.order) out[s.name as SceneName] = { from: s.from, duration: s.duration };
  return out;
};
export const SCENES = buildScenes();

// ---- Caption style ----
export const CAPTION_STYLE: CaptionStyle = {
  fontFamily: ANTON,
  accentBBeats: [], // single accent (cyan) — no second side
  accentA: COLORS.accent,
  accentB: COLORS.gold,
  text: COLORS.text,
  fontSize: 72,
};

// ---- Audio spec (VO lead + envelope-ducked bed + SFX at the prompt frames) ----
export const AUDIO_SPEC: AudioSpec = {
  vo: "vo.wav",
  voVolume: 0.95,
  music: "music-dark-tension.mp3",
  envelope: [
    { frame: 0, volume: 0.22 },
    { frame: 759, volume: 0.22 },
    { frame: 768, volume: 0.72 },
    { frame: 820, volume: 0.72 },
    { frame: TOTAL, volume: 0 },
  ],
  sfx: [
    { file: "sfx-reveal-hit.mp3", from: 60, durationInFrames: 60, volume: 0.95 },
    { file: "sfx-tick.mp3", from: 282, durationInFrames: 30, volume: 0.6 },
    { file: "sfx-whoosh.mp3", from: 384, durationInFrames: 45, volume: 0.5 },
    { file: "sfx-tick.mp3", from: 537, durationInFrames: 30, volume: 0.6 },
    { file: "sfx-reveal-hit.mp3", from: 691, durationInFrames: 60, volume: 0.9 },
  ],
};
