import { loadFont as loadAnton } from "@remotion/google-fonts/Anton";
import { loadFont as loadSpaceMono } from "@remotion/google-fonts/SpaceMono";
import { WIDTH, HEIGHT, FPS } from "../lib/safeArea";
import type { CaptionStyle } from "../lib/Captions";
import type { AudioSpec } from "../lib/AudioBed";
import voTiming from "./vo-timing.json";
import sceneOrder from "./scenes.json";

// F-002 — T. rex closer to you than to Stegosaurus. Generated by remotion-codegen on
// the shared lib (same vertical-timeline archetype as F-001, new data). Duration via
// calculateMetadata(vo-timing.total) — no DURATION const.

export { WIDTH, HEIGHT, FPS };
export const TOTAL: number = voTiming.total;

export const { fontFamily: ANTON } = loadAnton("normal", { weights: ["400"], subsets: ["latin"] });
export const { fontFamily: MONO } = loadSpaceMono("normal", { weights: ["400", "700"], subsets: ["latin"] });

// ---- Colors (navy/indigo depth; gold ancient Stego->T.rex / ice modern T.rex->today) ----
export const COLORS = {
  bgTop: "#0B1430",
  bgBottom: "#1C2A55",
  glow: "#2E4A8C",
  nebula: "#3A2C6B",
  text: "#F4F1E8",
  gold: "#F2B53C",
  ice: "#6FD3FF",
  rule: "#5B6BA8",
} as const;

// ---- Vertical deep-time geometry (SCALE-HONEST, computed from the dates) ----
// span = 150 Mya -> 0 = 150 My over 1200px => 8 px/My.
export const SPINE_X = 170;
export const SPINE_W = 14;
export const STEGO_Y = 300; // 150 Mya (top node)
export const TREX_Y = 972; // 66 Mya = (150-66)/150 = 56% down -> 300 + 0.56*1200
export const NOW_Y = 1500; // today (bottom node)
// Gap1 Stego->T.rex = 672px (84 My); Gap2 T.rex->now = 528px (66 My) -> 672:528 = 1.27 = 84:66.

export const CONTENT_LEFT = 300;
export const CONTENT_RIGHT = 40;
export const Y = { kicker: 360, hero: 900 } as const;

// ---- Scene ranges DERIVED from scenes.json + TOTAL (validated by check-tiling.mjs) ----
type SceneName =
  | "hook" | "beat1" | "beat2" | "beat3" | "beat4" | "beat5" | "beat6" | "loopBack";
const buildScenes = (): Record<SceneName, { from: number; duration: number }> => {
  const order = sceneOrder.order;
  const out = {} as Record<SceneName, { from: number; duration: number }>;
  order.forEach((s, i) => {
    const next = i + 1 < order.length ? order[i + 1].from : TOTAL;
    out[s.name as SceneName] = { from: s.from, duration: next - s.from };
  });
  return out;
};
export const SCENES = buildScenes();

// ---- Caption style ----
export const CAPTION_STYLE: CaptionStyle = {
  fontFamily: ANTON,
  accentBBeats: ["beat4", "beat5", "beat6"], // modern (ice) side
  accentA: COLORS.gold,
  accentB: COLORS.ice,
  text: COLORS.text,
  fontSize: 76,
};

// ---- Audio spec ----
export const AUDIO_SPEC: AudioSpec = {
  vo: "vo.wav",
  voVolume: 0.95,
  music: "music-dark-tension.mp3",
  envelope: [
    { frame: 0, volume: 0.22 },
    { frame: 645, volume: 0.22 },
    { frame: 654, volume: 0.72 },
    { frame: 700, volume: 0.72 },
    { frame: TOTAL, volume: 0 },
  ],
  sfx: [
    { file: "sfx-tick.mp3", from: 95, durationInFrames: 30, volume: 0.6 },
    { file: "sfx-tick.mp3", from: 206, durationInFrames: 30, volume: 0.6 },
    { file: "sfx-whoosh.mp3", from: 306, durationInFrames: 45, volume: 0.5 },
    { file: "sfx-whoosh.mp3", from: 447, durationInFrames: 45, volume: 0.5 },
    { file: "sfx-reveal-hit.mp3", from: 518, durationInFrames: 60, volume: 0.95 },
  ],
};
