import { loadFont as loadAnton } from "@remotion/google-fonts/Anton";
import { loadFont as loadSpaceMono } from "@remotion/google-fonts/SpaceMono";
import { WIDTH, HEIGHT, FPS } from "../lib/safeArea";
import type { CaptionStyle } from "../lib/Captions";
import type { AudioSpec } from "../lib/AudioBed";
import voTiming from "./vo-timing.json";
import sceneOrder from "./scenes.json";

// Resolved design tokens for F-001 (generated by remotion-codegen from the spec
// package). NO duration constant lives here — durationInFrames comes from
// calculateMetadata reading vo-timing.json `total` (the F-001 v1 hardcoded-DURATION
// bug is structurally impossible now).

export { WIDTH, HEIGHT, FPS };

// total = vo-timing.json `total` (= durationInFrames). Used only for the background
// drift span and scene math — NOT as the composition duration const.
export const TOTAL: number = voTiming.total;

// ---- Fonts ----
export const { fontFamily: ANTON } = loadAnton("normal", {
  weights: ["400"],
  subsets: ["latin"],
});
export const { fontFamily: MONO } = loadSpaceMono("normal", {
  weights: ["400", "700"],
  subsets: ["latin"],
});

// ---- Colors (navy/indigo depth, gold ancient / ice modern) ----
export const COLORS = {
  bgTop: "#0B1430",
  bgBottom: "#1C2A55",
  glow: "#2E4A8C",
  nebula: "#3A2C6B",
  text: "#F4F1E8",
  gold: "#F2B53C",
  ice: "#6FD3FF",
  rule: "#5B6BA8",
} as const;

// ---- Vertical timeline geometry (SCALE-HONEST, computed from the years) ----
// span = 2560 BC -> 1969 = 4,529 yrs over 1200px => 0.2650 px/yr
export const SPINE_X = 170;
export const SPINE_W = 14;
export const PYRAMID_Y = 300; // 2560 BC (top)
export const CLEO_Y = 960; // 69 BC = 2,491 yr after pyramid -> 55% down
export const MOON_Y = 1500; // 1969 (bottom)

// ---- Content lane (clear of the spine) ----
export const CONTENT_LEFT = 300;
export const CONTENT_RIGHT = 40;

export const Y = {
  kicker: 360,
  hero: 900,
} as const;

// ---- Scene frame ranges — DERIVED from scenes.json (the single source of truth,
// also read by check-tiling.mjs) + TOTAL. Contiguous, half-open: each scene runs to
// the next scene's `from`; the last runs to TOTAL. Validated to tile [0, TOTAL]. ----
type SceneName =
  | "hook" | "beat1" | "beat2" | "beat3" | "beat4" | "beat5" | "beat6" | "loopBack";

const buildScenes = (): Record<SceneName, { from: number; duration: number }> => {
  const order = sceneOrder.order;
  const out = {} as Record<SceneName, { from: number; duration: number }>;
  order.forEach((s, i) => {
    const next = i + 1 < order.length ? order[i + 1].from : TOTAL;
    out[s.name as SceneName] = { from: s.from, duration: next - s.from };
  });
  return out;
};
export const SCENES = buildScenes();

// ---- Caption style (drives lib/Captions; merge/override/accent rules in captions-core) ----
export const CAPTION_STYLE: CaptionStyle = {
  fontFamily: ANTON,
  accentBBeats: ["beat4", "beat5", "beat6"], // modern (ice) side
  accentA: COLORS.gold,
  accentB: COLORS.ice,
  text: COLORS.text,
  overrides: { "2,500": "~2,500", "2,000": "~2,000", "450": "~450" },
  fontSize: 76,
};

// ---- Audio spec (drives lib/AudioBed; VO lead + envelope-ducked bed + SFX) ----
export const AUDIO_SPEC: AudioSpec = {
  vo: "vo.wav",
  voVolume: 0.95,
  music: "music-dark-tension.mp3",
  // bed ducked 0.22 under the single merged speech region, releases + swells on
  // the silent tail, fades to 0 by `total` for a clean loop seam.
  envelope: [
    { frame: 0, volume: 0.22 },
    { frame: 855, volume: 0.22 },
    { frame: 864, volume: 0.72 },
    { frame: 922, volume: 0.72 },
    { frame: TOTAL, volume: 0 },
  ],
  sfx: [
    { file: "sfx-tick.mp3", from: 109, durationInFrames: 30, volume: 0.6 },
    { file: "sfx-tick.mp3", from: 259, durationInFrames: 30, volume: 0.6 },
    { file: "sfx-tick.mp3", from: 493, durationInFrames: 30, volume: 0.6 },
    { file: "sfx-whoosh.mp3", from: 397, durationInFrames: 45, volume: 0.5 },
    { file: "sfx-whoosh.mp3", from: 592, durationInFrames: 45, volume: 0.5 },
    { file: "sfx-reveal-hit.mp3", from: 702, durationInFrames: 60, volume: 0.95 },
  ],
};
